# Configs for sharanm.dev

title: "sharanm.dev"
name: "sharanm.dev"
email: sharan98m@gmail.com
url: "" #"http://www.pwills.com"
repository: "lightbulbmoment22617/lightbulbmoment22617.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
  
# settings for author profile
author:
  name   : "Sharan Maiya"
  avatar : "/assets/images/headshot.jpg"
  bio    : "I'm an undergraduate studying CS+Maths interested in stats, ML and data."
  location: "Edinburgh, Scotland"
  github : lightbulbmoment22617
  linkedin: sharanmaiya
  email  : sharan98m@gmail.com


# # comments by disqus
# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "pwills-com"

# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
